### ISSUE TITLE
The zero address `newAddress(0, 0)`  compilation failed.

### ISSUE THREAD

**Issue by verichenn** [tact-lang/tact#542] opened 2024-07-10 10:01 UTC
> tact-lang version: 1.4.0
```
contract Test {

    executor: Address?;

    receive ("test") {
        self.executor = newAddress(0, 0);
    }
}
```
Error: Invalid address hash length: 0

**Comment by anton-trunov** [comment] 2024-07-10 10:04
Duplicate of #515. Already fixed and will be released in v1.4.1

**Closed as completed by anton-trunov** 2024-07-10 10:04 UTC
Labels: scope: partial-eval
