### ISSUE TITLE
feat: `StringBuilder.append` should return `self`

### ISSUE THREAD

**Issue by 0kenx** [tact-lang/tact#213] opened 2024-03-29 22:15 UTC
## Problem

Currently `StringBuilder.append` is defined as `extends mutates fun append(self: StringBuilder, s: String);`. This does not allow chaining.

## Proposal

`StringBuilder.append` should return `self` with signature `extends mutates fun append(self: StringBuilder, s: String): StringBuilder;`. This would allow developers to write

```
...
body: beginComment().append("abc").append("def").asSlice();
```

instead of

```
let b: StringBuilder = beginComment();
b.append("abc");
b.append("def");
...
body: b.asSlice();
```

## Compatibility

This proposed feature does not have compatibility concerns. For legacy code the return value is simply not used, and no contract code modifications are necessary.

**Comment by anton-trunov** [comment] 2024-03-30 08:54
It's essentially a duplicate of #23

**Closed as completed** 2024-04-01 11:22 UTC
Labels: scope: stdlib
