### ISSUE TITLE
Tact produces invalid FunC code for modifying load function

### ISSUE THREAD

**Issue by Gusarich** [tact-lang/tact#211] opened 2024-03-29 15:02 UTC
This line:
```tact
let x: Int = beginCell().storeUint(0, 1).endCell().beginParse().loadUint(1);
```

Produces this FunC code:
```func
int $x = begin_parse(end_cell(store_uint(begin_cell(), 0, 1)))~load_uint(1);
```

Which results error:
```
error: lvalue expected before `~load_uint`
```

**Comment by 0kenx** [comment] 2024-04-07 20:38
Possible duplicate of #118

**Closed as completed** 2024-06-08 01:44 UTC
Labels: kind: bug, scope: typechecker
