### ISSUE TITLE
`Enum` type instead of define multiple constant variable

### ISSUE THREAD

**Issue by ZigBalthazar** [tact-lang/tact#431] opened 2024-06-17 21:03 UTC
regarding to `Tact` book [constants](https://docs.tact-lang.org/book/contracts#constants) documentation, it defined a non-friendly way to use the `Enum` concepts in Tact.
developers should define multiple constants instead of an enum, this way has some problem:

1. the defined constants to use instead of enums do not have a group:
 it means if we have to define an enum for the status of a user we should do this for now:
 ```ts
    const activeUser: Int = 0;
    const blockUser: Int = 1;
    const deletedUser: Int = 2;
 ```
 there is no consistency in naming and grouping.
 maybe it be better to do this like it(**_just syntax sample_**):
 
 ```ts
 enum user_status {
    ACTIVE = 0,
    BLOCK = 1,
    DELETED = 2
 }
 ```
 or 
 
 ```golang
const (
    userActive = 0
    userBlock = 1
    userDeleted = 2
)
 ```
 
2. type consistency:
 based on the above example from the tact book it is a mistake potential to use constant instead of 
 enum for types, for example:
 
  ```ts
    const activeUser: Int = 0;
    const blockUser: string = "1";
    const deletedUser: Int = 2;
 ```
 
Let's consider a solution for the mentioned problem by defining an `enum` type for tact and the tact compiler to make the tact language more developer-friendly. We can take inspiration from other languages, such as TypeScript, which changed the syntax and defined the enum type, while Golang used `const` in a grouping manner. There are various ways to implement this, and we should have a detailed discussion about the implementation of this feature in this issue.

**Comment by anton-trunov** [comment] 2024-06-17 21:15
Duplicate of #17

**Closed as completed by anton-trunov** 2024-06-17 21:15 UTC
