### ISSUE TITLE
Add `xor` support

### ISSUE THREAD

**Issue by 0kenx** [tact-lang/tact#235] opened 2024-04-10 09:18 UTC
`xor` should be added in stdlib.
```
@name(xor)
native xor(a: Int, b: Int): Int;
```
```
int xor(int x, int y) asm "XOR";
```

It's best to add it as an operator `^`.

**Comment by anton-trunov** [comment] 2024-04-11 07:55
Duplicate of #119

**Closed as completed by anton-trunov** 2024-04-11 07:55 UTC
Labels: kind: language feature

**Comment by 0kenx** [comment] 2024-05-08 16:49
BTW is there a bitwise NOT operator?

**Comment by anton-trunov** [comment] 2024-05-08 18:43
no, there is no bitwise NOT operator at the moment, thanks for point that out
